### ISSUE TITLE
Linux compilation 

### ISSUE THREAD

**Issue by lorforlinux** [medusabci/medusa-platform#45]
Hey @Serpeve @dmarcos97, you have build such an awesome project!

I am Deepak Khatri from [Upside Down Labs](https://github.com/upsidedownlabs/), we work on OpenSource DIY Neuroscience kits for students, researchers, and scientists. I am very excited to try out your software but, I don't find any instructions to compile/run it for Linux :(

Can you please share tips/instructions to run it on Linux?

**Comment by lorforlinux** [comment]
Okie, I am able to compile it now! 
Just installed everything from `dependencies.txt` and started with `python src/main.py`. 

I had to make these two changes:

under `src/gui/gui_utils.py` commented out one like and added another.
```
# from PyQt5.Qt import Qt
from PyQt5.QtCore import *
```

under `src/gui/main_window.py` commented out this line
```
# ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(medusaid)
```

**Comment by esantamariavazquez** [comment]
Hi @lorforlinux!

Glad to hear that you like MEDUSA!

It's great that you were able to run the project! Most features and apps should run just fine, but there are some differences in how the OS handles threads and processes that gave us some headaches in the past. For now we only officially support Windows, but Linux support is definitly one of the things that we will be improving in the coming months.

If you find more errors or weird behaviours, please let us know! It will be very helpful to develop the Linux version.

**Comment by lorforlinux** [comment]
Hey @esantamariavazquez , I'll probably be sending some patches as I try it out. BTW, why is it necessary to login to use the application?

**Comment by esantamariavazquez** [comment]
Great! We really appreciate the help. If we want to make MEDUSA the best open-source software for BCI and cognitive neuroscience experimentation, the involvent of the community is key! 

Regarding your question, the login is required as part of the app market system. Although the platform and most of the apps are free and open source (and they will remain like that forever), you can also upload private apps to the market specifically developed for projects, hospitals or other research groups. These apps are not freely available on the market and the developer can protect them through patents or other means. In these cases, the admin of the app grants permission to certain accounts to download, install and use the app, hence the necessity to login first. With this, we are able to fit all kinds of projects within MEDUSA, from small open source student projects to professional neurorehabilitation applications. 

Thanks again for trying out MEDUSA, let us know your opinion!

**Comment by yangyang1018** [comment]
Hi @lorforlinux!
 You said before that you have run the medusa programme on linux, I was wondering if you have managed to run itaca.app or any other application as the application contains .exe files, I am currently able to run medusa but not the .exe files that are contained in itaca, such as the mind cube, do you have any good suggestions?
